http{

   client_header_timeout 2;
   client_max_header_size 1MB;

  #  server {
  #  listen 0.0.0.0:8080;
  #  server_name api.localhost;
  
  # internal_api on;
  #}

    server {
    listen                 0.0.0.0:8080;
    server_name            localhost;
    client_max_body_size   200MB;
    client_max_header_size 10000;
    keepalive_timeout      2;
    client_header_timeout  5;
    client_body_timeout    20;
    keepalive_requests     2;
    
    # Home page
    location / {
    root ./www;
    index index.html;
    autoindex off;
  }
    # Directory listing
    location /list {
    root ./www/list;
    index test.html;
    autoindex on;
  }
    
    # Gallery
    location /upload {
        root             ./www/upload;
        index            index.html;
        allowed_methods  GET PUT DELETE POST;
        cgi             .py /usr/bin/python3;
    }

    location /dashboard {
      root ./www/dashboard;
      index index.html;
      autoindex off;
    }
    
    # CGI scripts
    location /cgi {
    allowed_methods POST GET PUT DELETE;
    root ./www/cgi;
    autoindex on;
    index list.py;
    cgi .py /usr/bin/python3;
  }
  
  location /wordpress {
    allowed_methods GET POST PUT DELETE HEAD OPTIONS;
    root ./www/wordpress;
    index index.php;
    cgi .php /bin/php-cgi;
  }
}
}
