
  server {
    listen        127.0.0.1:8080;
    server_name   localhost;
    
    client_max_body_size   10;
    
    location /test {
    root ./www;
    index index.html;
    autoindex off;
  }
  }
    
    server {
    listen                 0.0.0.0:8080;
    server_name            test.localhost;
    client_max_body_size   200MB;
    client_max_header_size 10000;
    keepalive_timeout      10;
    client_header_timeout  5;
    client_body_timeout    5;
    keepalive_requests     4;
    error_page 404         /404.html;
    
    # Home page
    location / {
    root ./www;
    index index.html;
    autoindex off;
  }
    
    # Directory listing
    location /list {
    root ./www/list;
    index index.html;
    autoindex on;
  }
    
    # Gallery
    location /upload {

        root             ./www/upload;
        index            index.html list.py;
        allowed_methods  GET PUT DELETE;
        cgi             .py /usr/bin/python3;
    }

    location /dashboard {
      root ./www/dashboard;
      index index.html;
      autoindex off;
    }
    
    # CGI scripts
    location /cgi {
    allowed_methods POST GET PUT DELETE;
    root ./www/cgi;
    autoindex on;
    index list.py;
    cgi .py /usr/bin/python3;
  }
  }

