server {
    listen                 8080;
    server_name            example.com;
    client_max_body_size   52428800;
    client_max_header_size 10000;
    keepalive_timeout      10;
    client_header_timeout  5;
    client_body_timeout    5;
    keepalive_requests     4;
    error_page 404         /404.html;

    # Home page
    location / {
        root ./www;
        index index.html;
        autoindex off;
    }

    # Directory listing
    location /list {
        root ./www/list;
        index index.html;
        autoindex on;
    }

    # Gallery
    location /upload {
        root             ./www/upload;
        index            index.html;
        allowed_methods  GET PUT DELETE;
    }

    location /dashboard {
      root ./www/dashboard;
      index index.html;
      autoindex off;
    }

    # CGI scripts
    location /cgi {
        allowed_methods POST GET PUT DELETE;
        root ./www/cgi;
        index index.html test.py;
        cgi .py /usr/bin/python3;
    }
}