services:
  webserv:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./db_data:/var/lib/mysql
